version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      DB_HOST: postgres
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./hotel-booking-frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:3000/api/v1/"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
